### ISSUE TITLE
Simplified Installation of Commodore

### ISSUE THREAD

**Issue by tobru** [projectsyn/commodore#166]
## Context

To install and use Commodore the current way is to use Poetry. This is an entry barrier as it isn't a common tool and mainly for _developing_ Commodore, not for _using_ Commodore.

Engineer a way to make installation and usage of Commodore very easy:
* `pip install commodore`
* `apt install commodore`
* `yum install commodore`
* `yay commodore`
* `brew install commodore`

## Alternatives

The alternative would be to provide a Docker alias as documented at https://syn.tools/commodore/running-commodore.html.

This brings in the dependency of having Docker running and is error prone because of issues with volume permissions.

**Comment by simu** [comment]
Publishing commodore on PyPI should be straight-forward with `poetry build && poetry publish` (cf. https://python-poetry.org/docs/cli/#publish)

**Comment by srueg** [comment]
> Publishing commodore on PyPI should be straight-forward with `poetry build && poetry publish` (cf. https://python-poetry.org/docs/cli/#publish)

Might be a little more complicated since we have to include the platform specific Helm bindings. Not sure how this is handled by PyPI packages.

**Comment by simu** [comment]
Hmm, true. However I don't think if you get the Helm bindings if you `pip install kapitan` either. If you did, we wouldn't have to worry about them in the first place.

**Comment by nunojusto** [comment]
Look at https://github.com/appuio/openshift4-docs/pull/39
The alias needs some fixes

**Comment by tobru** [comment]
Also checkout https://www.pyinstaller.org/ (and alternatives)

**Comment by chrisglass** [comment]
A solution to this problem is implemented as part of https://github.com/deepmind/kapitan/pull/631 - once the pull request is approved/merged, the workflow to install commodore becomes a simple:

```
pip install commodore
```

This will require to add a dependency to the python-packaged helm bindings in commodore's list of dependencies once the official kapitan package for the bindings is available, but this is a trivial change.

**Comment by simu** [comment]
The PyPI commodore package already exists at https://pypi.org/project/syn-commodore/ and will be usable without requiring building a Go library or copying it to the correct place with #358

**Comment by simu** [comment]
Since #376, commodore can be installed from PyPI on both Linux and macOS. We've looked at building distribution packages, but since a number of the Python dependencies used by Kapitan and Commodore are not available in the distribution repos, the effort to build packages would far outweigh the added value.
