### ISSUE TITLE
Configurable revisions for global and tenant config repositories

### ISSUE THREAD

**Issue by corvus-ch** [projectsyn/commodore#198]
Commodore always clones the master branch of the global and the tenant config repositories. Using the `--local` flag, one can change this behavior. While hacking around with Commodore, using local mode might not be possible. Having the ability to use other references (tag, commit) would solve this.

This would have helped in #195. There we had to add a temporary commit that had to be removed right before the merge.

**Comment by corvus-ch** [comment]
This can be implemented simply by implementing some flags with commodore. This most certainly would be a 80/20 solution. The drawback would be, the version pinning is not persistent.

In order to tackle this, we would need to extend the Tenant and Cluster objects. Both objects would allow to set version of the global and the tenant config repository. Tenant would take precedence over the global default and Cluster would take precedence over Tenant.

Which approach shall we follow?

**Comment by simu** [comment]
I think long term, we'll want the solution which allows specifying a version of the global and tenant repository in the Tenant and Cluster API objects.

Please note that this issue is loosely coupled to #171, which aims to make the global configuration repository configurable per tenant/cluster, rather than requiring the counterintuitive GLOBAL_GIT_BASE parameter.

Short term, both features could be implemented by (ab)using the existing facilities to define custom facts per cluster (tenant-scoped custom facts are not supported at the moment).
