### ISSUE TITLE
Add support for http proxies

### ISSUE THREAD

**Issue by rxbn** [projectsyn/commodore#209]
## Context

I cannot develop syn components locally since my business laptop is behind a web proxy. Is it possible to respect HTTP_PROXY, HTTPS_PROXY and NO_PROXY variables?

## Alternatives

No alternative.

**Comment by srueg** [comment]
Hi @rxbn 

It should already be possible to set the `HTTP_PROXY` and `HTTPS_PROXY` env vars to do all the API calls via the proxy.
For the Git operations we use the [GitPython](https://gitpython.readthedocs.io/en/stable/#) library where some work needs to be done to support HTTP proxies: https://github.com/projectsyn/commodore/blob/master/commodore/git.py#L65

You could also try to only use Git repos via `ssh://` instead of `https://` to skip the proxy.

Please let us know what parts exactly don't work for you and we can look into supporting HTTP proxies.

**Comment by rxbn** [comment]
I was able to fix it with @simu 

We had to change the jsonnet dependencies and componentes to use ssh instead of https. Just like you've mentioned.
And we also had to set the env var `REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt` in order to trust our corporate proxy cert.

This issue can be closed now :)
