### ISSUE TITLE
Maintain Kapitan fork for Commodore

### ISSUE THREAD

**Issue by tobru** [projectsyn/commodore#261]
## Context

Kapitan lately had some delays in releases which blocks Commodore from moving forward. As a solution, until Kapitan development and releases can come up to speed again, we should include a fork of Kapitan with our patches into Commodore. This can be done in different ways, the best one still needs to be figured out.

Possible options:

* Point to a Git repo and specific Git ref in the dependency management
* Include Kapitan as a Git sub-module (like Kapitan does with Reclass)

## Alternatives

Wait for Kapitan releases to happen, which isn't up to speed currently.

**Comment by srueg** [comment]
I'd vote for option 1 (point Poetry to Git repo) since it's the least invasive option and can easily be reverted once we don't need the fork anymore.
This would mean some changes in our Docker build since it makes assumptions about locations of certain files which would change:
* https://github.com/projectsyn/commodore/blob/master/Dockerfile#L42
* https://github.com/projectsyn/commodore/blob/master/Dockerfile#L67
* https://github.com/projectsyn/commodore/blob/master/Dockerfile#L71

Also we used this approach before to test bugfixes before they were released upstream and with exception of the Docker build everything just worked ™️ .
