### ISSUE TITLE
kube-libsonnet is using soon deprecated API versions

### ISSUE THREAD

**Issue by megian** [projectsyn/commodore#627]
## Context
With Kubernetes v1.25 a lot of API get [deprecated](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-25). The latest version of kube-libsonnet still using it.
policy/v1beta1: https://github.com/bitnami-labs/kube-libsonnet/blob/23fe9f1c4905c174c90ea1b6681fb790b6715a6c/kube.libsonnet#L268
batch/v1beta1: https://github.com/bitnami-labs/kube-libsonnet/blob/23fe9f1c4905c174c90ea1b6681fb790b6715a6c/kube.libsonnet#L531

## Alternatives
* Drop the support of kube-libsonnet in Commodore

**Comment by megian** [comment]
See bitnami-labs#75.

**Comment by simu** [comment]
Possible options for making sure kube-libsonnet is compatible with K8s 1.25+ (no particular order):
* Hope that upstream accepts and merges https://github.com/bitnami-labs/kube-libsonnet/pull/76
* Vendor the library in Commodore (alongside `commodore.libjsonnet`) and take over maintenance for it
* Create a fork of https://github.com/bitnami-labs/kube-libsonnet in https://github.com/projectsyn, patch the fork and update Commodore to fetch the file from the projectsyn fork

**Comment by simu** [comment]
After a slightly closer look. https://github.com/jsonnet-libs/k8s-libsonnet is not a drop-in replacement for kube-libsonnet, but actually looks much nicer (and more complete -- not too surprising since the base implementation is generated from the K8s API spec). However, we could probably engineer a migration path by providing a vendored kube-libsonnet which emits deprecation warnings informing users that they should switch to k8s-libsonnet.

**Comment by megian** [comment]
The components projectsyn/component-kyverno and projectsyn/component-vault are affected and source of this issue.
