### ISSUE TITLE
Update Cookiecutter Component Template

### ISSUE THREAD

**Issue by srueg** [projectsyn/commodore#72]
Update the [Cookiecutter template](https://github.com/projectsyn/commodore/tree/master/component-template) for new components to include the following:

- [x] A license: BSD-3-Clause
- [x] Option to base a component on a Helm chart (i.e. `--helm`) -> see  #118.
- [x] Add GitHub actions (jsonnet & yaml lint, others tbd)
- [x] `doc/` subfolder?
- [x] README.adoc template
- [x] CHANGELOG.adoc template
- [x] GitHub templates

How does the release process look like? Keyword: Changelog?

* Release process automation
* GitHub release preparation

**Comment by tobru** [comment]
@corvus-ch Please do a real life experiment with https://github.com/appuio/component-openshift4-oauth/issues/5

**Comment by corvus-ch** [comment]
The example in the openshift4-oauth component is done. It can be included in the cookiecutter.

Thoughts on how to improve:

GitHub strongly suggests to have a CONTRIBUTING.md file within each repository. For components we would (ideally) have the same file in each and every component repository. Instead of keeping them all in sync, we might opt to move that to somewhere at syn.tools and just place a link into CONTRIBUTING.md.

**Comment by corvus-ch** [comment]
@srueg Can we extract the _option to base a component on a Helm chart_ to an issue on its own?

**Comment by srueg** [comment]
Sure :+1:

**Comment by corvus-ch** [comment]
In addition, also a code of conduct got added to the template.

I do not yet have an answer on how to do release automation.

**Comment by tobru** [comment]
Done in #117
